[package]
name = "jwt-validator"
version = "0.1.0"
edition = "2024"

[dependencies]
jsonwebtoken = "9.3.1"
serde = {version = "1.0.219", features = ["derive"]}
# serde_json = "1.0"

[dev-dependencies]
rsa = { version = "0.9.8"}
base64 = "0.22"
rand = "0.9.0"
