[package]
name = "pallet-jwt"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
log.workspace = true
scale-info.workspace = true
traits-authn.workspace = true
frame-support.workspace = true
